### ISSUE TITLE
Debugging: "Cannot connect to runtime process" ECONNREFUSED

### ISSUE THREAD

**Issue by JPGygax68** [frederiksen/angular-electron-boilerplate#2]
I'm getting the above error after downloading (can provide more output if needed) and using the boilerplate as per the instructions in the readme. The only deviation was that I threw in an `npm audit fix` after `npm install` reported a single security, which was fixed successfully.

**Comment by frederiksen** [comment]
Hi @JPGygax68 Can you share your *Debug Console*? Here's mine:

![debug-console](https://user-images.githubusercontent.com/10465424/66330865-93920380-e931-11e9-9e61-11abfe13955b.PNG)

I'm thinking of two things. 1) Can you have a firewall that blocks communication on port 9222? 2) Or I have heard that sometimes you need to kill all Chrome instances before the debugger starts a new Chrome instance, so you can try that.

**Comment by JPGygax68** [comment]
I went into Task Manager to terminate the dozen or so of Chrome notification tasks, no change.
Is the firewall relevant to localhost connections on Windows? I never knew for sure. I would expect a dialog to pop up on first use though.
Here's the log:
```
Verbose logs are written to:
C:\Users\gygax\AppData\Local\Temp\vscode-chrome-debug.txt
2019-10-7, 17:03:57.571 UTC
OS: win32 x64
Adapter node: v10.11.0 x64
vscode-chrome-debug-core: 6.8.0
debugger-for-chrome: 4.12.0
From client: initialize({"clientID":"vscode","clientName":"Visual Studio Code","adapterID":"chrome","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en-us"})
To client: {"seq":0,"type":"response","request_seq":1,"command":"initialize","success":true,"body":{"exceptionBreakpointFilters":[{"label":"All Exceptions","filter":"all","default":false},{"label":"Uncaught Exceptions","filter":"uncaught","default":false}],"supportsConfigurationDoneRequest":true,"supportsSetVariable":true,"supportsConditionalBreakpoints":true,"supportsCompletionsRequest":true,"supportsHitConditionalBreakpoints":true,"supportsRestartFrame":true,"supportsExceptionInfoRequest":true,"supportsDelayedStackTraceLoading":true,"supportsValueFormattingOptions":true,"supportsEvaluateForHovers":true,"supportsLoadedSourcesRequest":true,"supportsBreakpointLocationsRequest":true,"supportsRestartRequest":true,"supportsSetExpression":true,"supportsLogPoints":true}}
To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"ClientRequest/initialize","data":{"Versions.DebugAdapterCore":"6.8.0","Versions.DebugAdapter":"4.12.0","successful":"true","timeTakenInMilliseconds":"5.564399","requestType":"request"}}}
From client: attach({"name":"Renderer","type":"chrome","request":"attach","trace":"verbose","port":9222,"sourceMaps":true,"webRoot":"D:\\Training\\angular\\angular-electron","timeout":10000,"sourceMapPathOverrides":{"./*":"D:\\Training\\angular\\angular-electron/src/renderer/*"},"__sessionId":"8de631c1-320a-4bca-82be-cd5bb0090d7c"})
To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"debugStarted","data":{"Versions.DebugAdapterCore":"6.8.0","Versions.DebugAdapter":"4.12.0","request":"attach","args":["name","type","request","trace","port","sourceMaps","webRoot","timeout","sourceMapPathOverrides","__sessionId","pathMapping","skipFileRegExps","targetFilter","smartStep","showAsyncStacks"]}}}
Getting browser and debug protocol version via http://127.0.0.1:9222/json/version
Discovering targets via http://127.0.0.1:9222/json/list
HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9222
There was an error connecting to http://127.0.0.1:9222/json/version : connect ECONNREFUSED 127.0.0.1:9222
HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9222
Discovering targets via http://127.0.0.1:9222/json
HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9222
Getting browser and debug protocol version via http://127.0.0.1:9222/json/version
Discovering targets via http://127.0.0.1:9222/json/list
HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9222
There was an error connecting to http://127.0.0.1:9222/json/version : connect ECONNREFUSED 127.0.0.1:9222
HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9222
Discovering targets via http://127.0.0.1:9222/json
HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9222
Getting browser and debug protocol version via http://127.0.0.1:9222/json/version
Discovering targets via http://127.0.0.1:9222/json/list
HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9222
Discovering targets via http://127.0.0.1:9222/json
HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9222
There was an error connecting to http://127.0.0.1:9222/json/version : connect ECONNREFUSED 127.0.0.1:9222
HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9222
To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"ClientRequest/attach","data":{"Versions.DebugAdapterCore":"6.8.0","Versions.DebugAdapter":"4.12.0","successful":"false","exceptionType":"firstChance","exceptionMessage":"Cannot connect to runtime process, timeout after {_timeout} ms - (reason: {_error}).","exceptionName":"Error","exceptionStack":"Error: Cannot connect to runtime process, timeout after {_timeout} ms - (reason: {_error}).\n    at Object.runtimeConnectionTimeout (errors.js:91:12)\n    at utils.retryAsync.catch.err (chromeConnection.js:110:49)\n    at process._tickCallback (internal/process/next_tick.js:68:7)","exceptionId":"2010","timeTakenInMilliseconds":"12462.7686","requestType":"request"}}}
To client: {"seq":0,"type":"response","request_seq":2,"command":"attach","success":false,"message":"Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:9222).","body":{"error":{"id":2010,"format":"Cannot connect to runtime process, timeout after {_timeout} ms - (reason: {_error}).","variables":{"_error":"Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:9222","_timeout":"10000"}}}}
```

**Comment by frederiksen** [comment]
Take a look at this: https://github.com/Microsoft/vscode-chrome-debug#cannot-connect-to-the-target-connect-econnrefused-1270019222

**Comment by nazar322** [comment]
I too had this problem. I managed to solve it.

First of all, check if nothing has occupied port 9222.
Run `netstat -ab` and see if there any processes listening to that port.
In my case, I had two processes listening on the port.

Then notice that renderer debugger is configured for attachment, not to launch itself. It means before you run the renderer debug instance you have to have the app running. The only problem is that when you run `npm start` it launches the instance without listening to port 9222. Go to `package.json` and change `"start": "electron ."` to `"start": "electron . --remote-debugging-port=9222"`. Then I was able to connect after I ran the app with `npm start`

For the same reason, it works when you launch `Main + Renderer` profile, because of `Main` profile launches electron with `--remote-debugging-port=9222` argument.
